# Home Assistant integration API. The daemon exposes the dashboard's controls and
# sensors over an authenticated LAN HTTP + SSE API (see daemon/ha.go); the
# first-party HACS custom integration (../../integration) connects to it. This
# replaces the old MQTT bridge — there is no broker.
#
# On by default: it opens a single LAN port (not the internet) and advertises the
# device over mDNS so Home Assistant can auto-discover it. Every request carries a
# bearer token — either provisioned via tokenFile / config import, or generated by
# the daemon on first boot and shown on the on-screen Config → Info panel (paste
# it into Home Assistant when adding the integration). The primary :8080 admin
# surface stays loopback-only.
{ config, lib, ... }:
let
  cfg = config.dashboardAssistant.haApi;
in
{
  options.dashboardAssistant.haApi = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Serve the Home Assistant integration API on the LAN and advertise the
        device over mDNS. Disable to keep the device off Home Assistant entirely
        (the loopback admin surface is unaffected).
      '';
    };

    port = lib.mkOption {
      type = lib.types.port;
      default = 8081;
      description = "TCP port for the LAN Home Assistant API listener.";
    };

    pairAutoConfirm = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Hold the pairing window permanently open so Home Assistant can fetch the
        API token with no on-screen confirmation — zero-touch enrollment for a
        preprovisioned fleet on a trusted network. Leave off for the default
        presence-gated flow, where the operator presses "Pair" on the Config
        screen to open a short window. The token is only ever handed out over the
        LAN listener, never broadcast in mDNS.
      '';
    };

    tokenFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = "/var/lib/dashboard-assistant/api.env";
      description = ''
        Optional systemd EnvironmentFile providing a fixed API token:

          DASHBOARD_ASSISTANT_API_TOKEN=some-long-secret

        Keep it off the Nix store (which is world-readable) so the token stays
        private. Leave null to let the daemon generate and persist a per-device
        token on first boot (shown on the Config → Info panel).
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Open just the API port on the LAN (never the internet).
    networking.firewall.allowedTCPPorts = [ cfg.port ];

    # Merges with the DASHBOARD_ASSISTANT_ADDR set in daemon.nix.
    systemd.services.dashboard-assistant-daemon = {
      environment = {
        DASHBOARD_ASSISTANT_API_ADDR = ":${toString cfg.port}";
      }
      // lib.optionalAttrs cfg.pairAutoConfirm {
        DASHBOARD_ASSISTANT_PAIR_AUTO = "1";
      };
      serviceConfig = lib.mkIf (cfg.tokenFile != null) {
        EnvironmentFile = cfg.tokenFile;
      };
    };

    # Advertise the device over mDNS so Home Assistant discovers it (zeroconf).
    # avahi.openFirewall (default true) handles UDP 5353; no Go mDNS dependency.
    services.avahi = {
      enable = true;
      # Never advertise on loopback — Home Assistant would otherwise try to reach
      # the service on its own 127.0.0.1. Multiple real addresses (IPv4 + IPv6)
      # are fine: the config flow de-duplicates discovery by the device's stable
      # node id (GET /api/ha/identify), so one device stays one entry.
      denyInterfaces = [ "lo" ];
      publish = {
        enable = true;
        userServices = true;
      };
      extraServiceFiles.dashboard-assistant = ''
        <?xml version="1.0" standalone='no'?>
        <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
        <service-group>
          <name replace-wildcards="yes">Dashboard Assistant on %h</name>
          <service>
            <type>_dashboard-assistant._tcp</type>
            <port>${toString cfg.port}</port>
          </service>
        </service-group>
      '';
    };
  };
}
